# Generated by Django 6.0.2 on 2026-02-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=50)),
                ('available_status', models.CharField(max_length=50)),
                ('equipment_img', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_date', models.DateField()),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.equipment')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='mess.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='mess.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('feedback', models.CharField(max_length=1000)),
                ('rating_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.equipment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.user')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mess.user'),
        ),
    ]
