# Generated by Django 6.0.2 on 2026-04-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='long',
            field=models.FloatField(),
        ),
    ]
