# Generated by Django 6.0.2 on 2026-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_user_lat_alter_user_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_img',
            field=models.ImageField(upload_to='equipment/'),
        ),
    ]
